package com.example.chatnova.core.localization

import com.example.chatnova.domain.model.AppLanguage

object AppStrings {
    fun get(key: String, language: AppLanguage): String {
        return when (language) {
            AppLanguage.BANGLA -> banglaStrings[key] ?: englishStrings[key] ?: key
            AppLanguage.ENGLISH -> englishStrings[key] ?: key
        }
    }

    private val englishStrings = mapOf(
        "app_name" to "ChatNova",
        "tagline" to "Connect, Chat & Play in Real-Time",
        "splash_sub" to "Next-Gen Social & Gaming Platform",
        "onboarding_title_1" to "Realtime & Offline Chat",
        "onboarding_desc_1" to "Chat seamlessly with friends even without internet. Messages automatically sync when reconnected.",
        "onboarding_title_2" to "Live Multiplayer Games",
        "onboarding_desc_2" to "Challenge friends to turn-based games like Tic Tac Toe, Chess, and climb the global leaderboards.",
        "onboarding_title_3" to "Social Connections",
        "onboarding_desc_3" to "Make friends, build custom groups, earn achievements, and unlock exclusive Nova profile badges.",
        "skip" to "Skip",
        "next" to "Next",
        "get_started" to "Get Started",
        "login_title" to "Welcome Back",
        "login_sub" to "Sign in to enter the Nova universe",
        "email" to "Email Address",
        "password" to "Password",
        "confirm_password" to "Confirm Password",
        "forgot_password" to "Forgot Password?",
        "sign_in" to "Sign In",
        "sign_up" to "Sign Up",
        "register_title" to "Create Account",
        "register_sub" to "Join thousands of players and chatters",
        "username" to "Username",
        "display_name" to "Display Name",
        "demo_login" to "Explore as Guest",
        "already_account" to "Already have an account? Sign In",
        "need_account" to "Don't have an account? Sign Up",
        "home" to "Home",
        "chats" to "Chats",
        "games" to "Games",
        "friends" to "Friends",
        "profile" to "Profile",
        "settings" to "Settings",
        "online" to "Online",
        "offline" to "Offline",
        "playing" to "In Game",
        "quick_match" to "Quick Game",
        "tictactoe_title" to "Tic Tac Toe",
        "tictactoe_desc" to "Classic 3x3 match against friends or AI",
        "play_now" to "Play Now",
        "featured_games" to "Featured Games",
        "active_friends" to "Active Friends",
        "recent_chats" to "Recent Conversations",
        "see_all" to "See All",
        "new_chat" to "New Chat",
        "search_chats" to "Search chats or friends...",
        "search_friends" to "Search by name or @username...",
        "requests" to "Friend Requests",
        "accept" to "Accept",
        "decline" to "Decline",
        "add_friend" to "Add Friend",
        "friends_count" to "Friends",
        "games_played" to "Games",
        "wins" to "Wins",
        "achievements" to "Achievements",
        "edit_profile" to "Edit Profile",
        "appearance" to "Appearance",
        "theme" to "Theme Mode",
        "language" to "App Language",
        "notifications" to "Push Notifications",
        "privacy" to "Privacy & Security",
        "about" to "About ChatNova",
        "logout" to "Log Out",
        "status_synced" to "All messages synced",
        "system_default" to "System Default",
        "dark_mode" to "Dark Mode",
        "light_mode" to "Light Mode"
    )

    private val banglaStrings = mapOf(
        "app_name" to "চ্যাটনোভা",
        "tagline" to "রিয়েল-টাইমে যোগাযোগ, চ্যাট ও গেম খেলুন",
        "splash_sub" to "আধুনিক সোশ্যাল ও গেমিং প্ল্যাটফর্ম",
        "onboarding_title_1" to "রিয়েলটাইম ও অফলাইন চ্যাট",
        "onboarding_desc_1" to "ইন্টারনেট ছাড়াও বন্ধুদের সাথে চ্যাট করুন। সংযোগ ফিরলেই মেসেজ স্বয়ংক্রিয়ভাবে সিঙ্ক হবে।",
        "onboarding_title_2" to "লাইভ মাল্টিপ্লেয়ার গেমস",
        "onboarding_desc_2" to "বন্ধুদের সাথে টিক ট্যাক টো, দাবা খেলুন এবং গ্লোবাল লিডারবোর্ডে শীর্ষে উঠুন।",
        "onboarding_title_3" to "বন্ধুত্ব ও সোশ্যাল নেটওয়ার্ক",
        "onboarding_desc_3" to "নতুন বন্ধু বানান, গ্রুপ তৈরি করুন এবং অনন্য ব্যাজ ও অর্জন আনলক করুন।",
        "skip" to "এড়িয়ে যান",
        "next" to "পরবর্তী",
        "get_started" to "শুরু করুন",
        "login_title" to "স্বাগতম",
        "login_sub" to "নোভা জগতে প্রবেশ করতে সাইন ইন করুন",
        "email" to "ইমেইল ঠিকানা",
        "password" to "পাসওয়ার্ড",
        "confirm_password" to "পাসওয়ার্ড নিশ্চিত করুন",
        "forgot_password" to "পাসওয়ার্ড ভুলে গেছেন?",
        "sign_in" to "সাইন ইন",
        "sign_up" to "সাইন আপ",
        "register_title" to "নতুন অ্যাকাউন্ট তৈরি করুন",
        "register_sub" to "হাজারো খেলোয়াড় ও বন্ধুদের সাথে যুক্ত হোন",
        "username" to "ব্যবহারকারীর নাম",
        "display_name" to "প্রদর্শিত নাম",
        "demo_login" to "অতিথি হিসেবে ঘুরে দেখুন",
        "already_account" to "ইতিমধ্যে অ্যাকাউন্ট আছে? সাইন ইন করুন",
        "need_account" to "অ্যাকাউন্ট নেই? সাইন আপ করুন",
        "home" to "হোম",
        "chats" to "চ্যাট",
        "games" to "গেমস",
        "friends" to "বন্ধু",
        "profile" to "প্রোফাইল",
        "settings" to "সেটিংস",
        "online" to "অনলাইন",
        "offline" to "অফলাইন",
        "playing" to "গেমে আছেন",
        "quick_match" to "দ্রুত ম্যাচ",
        "tictactoe_title" to "টিক ট্যাক টো",
        "tictactoe_desc" to "বন্ধুদের সাথে ক্লাসিক ৩x৩ ম্যাচ",
        "play_now" to "এখনই খেলুন",
        "featured_games" to "জনপ্রিয় গেমস",
        "active_friends" to "অনলাইন বন্ধুরা",
        "recent_chats" to "সাম্প্রতিক কথোপকথন",
        "see_all" to "সব দেখুন",
        "new_chat" to "নতুন চ্যাট",
        "search_chats" to "চ্যাট বা বন্ধু খুঁজুন...",
        "search_friends" to "নাম বা @ইউজারনেম দিয়ে খুঁজুন...",
        "requests" to "ফ্রেন্ড রিকোয়েস্ট",
        "accept" to "গ্রহণ করুন",
        "decline" to "বাতিল",
        "add_friend" to "বন্ধু যোগ করুন",
        "friends_count" to "বন্ধু",
        "games_played" to "ম্যাচ",
        "wins" to "জয়",
        "achievements" to "অর্জনসমূহ",
        "edit_profile" to "প্রোফাইল সম্পাদনা",
        "appearance" to "দৃশ্যপট",
        "theme" to "থিম মোড",
        "language" to "অ্যাপের ভাষা",
        "notifications" to "পুশ নোটিফিকেশন",
        "privacy" to "গোপনীয়তা ও নিরাপত্তা",
        "about" to "চ্যাটনোভা সম্পর্কে",
        "logout" to "লগআউট",
        "status_synced" to "সব মেসেজ সিঙ্ক করা হয়েছে",
        "system_default" to "সিস্টেম ডিফল্ট",
        "dark_mode" to "ডার্ক মোড",
        "light_mode" to "লাইট মোড"
    )
}
